packages:
  - "apps/*"
  - "packages/*"
  - "packages/generators/*"

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
