// Theme content packs. The generator/solver code never changes to add a
// theme — only this data grows. Each pack needs enough names to cover the
// largest supported grid (8 suspects) with room to shuffle, and enough
// objects to give every suspect a distinct one.
export interface ThemeContent {
  /** Stable id, matched against MYSTERY_THEMES in @kdp/shared. */
  id: string;
  name: string;
  roomNames: string[];
  landmarkNames: string[];
  suspectFirstNames: string[];
  suspectLastNames: string[];
  /**
   * The evidence layer's object pool — every suspect carries exactly one
   * distinct entry. Needs at least as many entries as the largest grid
   * size, and reads best when the objects are plausible murder weapons
   * for the setting.
   */
  objectNames: string[];
}

export const MANOR_THEME: ThemeContent = {
  id: "manor",
  name: "Blackwood Manor",
  roomNames: [
    "Library",
    "Drawing Room",
    "Conservatory",
    "Billiard Room",
    "Kitchen",
    "Wine Cellar",
    "Study",
    "Ballroom",
    "Servants' Hall",
    "Gallery",
  ],
  landmarkNames: [
    "grandfather clock",
    "chess table",
    "bookshelf",
    "fireplace",
    "portrait",
    "piano",
    "globe",
    "vase of lilies",
    "suit of armor",
    "writing desk",
  ],
  suspectFirstNames: [
    "Victor",
    "Ursula",
    "Cordelia",
    "Oscar",
    "Baxter",
    "Emil",
    "Fenna",
    "Mara",
    "Tomas",
    "Elena",
    "Roland",
    "Wanda",
    "Sven",
    "Priya",
    "Warren",
    "Ophelia",
  ],
  suspectLastNames: [
    "Voss",
    "Reid",
    "Cho",
    "Ashford",
    "Blackwood",
    "Fenwick",
    "Lockhart",
    "Marsh",
    "Doyle",
    "Whitfield",
  ],
  objectNames: [
    "brass candlestick",
    "lead pipe",
    "coil of rope",
    "silver letter opener",
    "duelling pistol",
    "crystal decanter",
    "iron poker",
    "garrote wire",
    "vial of laudanum",
    "marble bookend",
    "riding crop",
    "ceremonial dagger",
  ],
};

export const FARM_THEME: ThemeContent = {
  id: "farm",
  name: "Sunnybrook Farm",
  roomNames: [
    "Main Barn",
    "Hayloft",
    "Stable",
    "Vegetable Garden",
    "Tool Shed",
    "Pantry",
    "Milking Parlor",
    "Grain Silo",
    "Chicken Coop",
    "Cider Press",
  ],
  landmarkNames: [
    "wheelbarrow",
    "hay bale",
    "water trough",
    "vegetable patch",
    "milk churn",
    "tractor",
    "feed sack",
    "apple crate",
    "weather vane",
    "coil of fencing",
  ],
  suspectFirstNames: [
    "Lena",
    "Silas",
    "Marta",
    "Dewey",
    "Corinne",
    "Abel",
    "Hattie",
    "Josiah",
    "Nell",
    "Rufus",
    "Clara",
    "Amos",
    "Etta",
    "Boone",
    "Sadie",
    "Gideon",
  ],
  suspectLastNames: [
    "Harrow",
    "Pike",
    "Colter",
    "Nash",
    "Buckley",
    "Rains",
    "Ellery",
    "Stubbs",
    "Vance",
    "Cade",
  ],
  objectNames: [
    "pitchfork",
    "hand scythe",
    "length of baling wire",
    "cast-iron skillet",
    "pruning shears",
    "horseshoe",
    "bottle of pesticide",
    "hay hook",
    "shovel",
    "milking stool",
    "axe handle",
    "sack of lye",
  ],
};

export const CAMP_THEME: ThemeContent = {
  id: "camp",
  name: "Lakeside Camp",
  roomNames: [
    "Boathouse",
    "Mess Tent",
    "Archery Range",
    "Cabin Row",
    "Campfire Ring",
    "Craft Lodge",
    "Infirmary",
    "Dock",
    "Storeroom",
    "Lookout Tower",
  ],
  landmarkNames: [
    "canoe rack",
    "bonfire pit",
    "bug-zapper lamp",
    "archery target",
    "cooler chest",
    "flagpole",
    "bunk ladder",
    "first-aid box",
    "rope swing",
    "stack of firewood",
  ],
  suspectFirstNames: [
    "Kira",
    "Desmond",
    "Paloma",
    "Trent",
    "Marisol",
    "Yusuf",
    "Bree",
    "Colton",
    "Ingrid",
    "Rafael",
    "Tamsin",
    "Errol",
    "Juno",
    "Micah",
    "Delphine",
    "Auggie",
  ],
  suspectLastNames: [
    "Alvarez",
    "Okafor",
    "Sandoval",
    "Brenner",
    "Halloway",
    "Nakamura",
    "Devlin",
    "Ferreira",
    "Kowalski",
    "Mbeki",
  ],
  objectNames: [
    "hunting knife",
    "aluminum canoe paddle",
    "signal flare",
    "hatchet",
    "length of climbing rope",
    "archery arrow",
    "tent stake",
    "heavy flashlight",
    "bottle of white gas",
    "cast-iron dutch oven",
    "boat anchor",
    "carabiner chain",
  ],
};

export const MESS_HALL_THEME: ThemeContent = {
  id: "messHall",
  name: "Barracks Mess Hall",
  roomNames: [
    "Mess Hall",
    "Galley",
    "Cold Store",
    "Officers' Table",
    "Scullery",
    "Supply Room",
    "Boiler Room",
    "Quartermaster's Office",
    "Loading Bay",
    "Bunk Row",
  ],
  landmarkNames: [
    "steam kettle",
    "serving line",
    "ration crate",
    "coffee urn",
    "walk-in freezer door",
    "mop bucket",
    "notice board",
    "stack of mess trays",
    "knife rack",
    "grease trap",
  ],
  suspectFirstNames: [
    "Franco",
    "Wanda",
    "Joaquin",
    "Esme",
    "Vivianna",
    "Dmitri",
    "Aurelio",
    "Beatriz",
    "Karel",
    "Noor",
    "Tobias",
    "Halina",
    "Ravi",
    "Simone",
    "Ivo",
    "Magda",
  ],
  suspectLastNames: [
    "Vargas",
    "Petrov",
    "Lindqvist",
    "Oyelaran",
    "Bauer",
    "Castellanos",
    "Novak",
    "Rahimi",
    "Duarte",
    "Sorensen",
  ],
  objectNames: [
    "meat cleaver",
    "cast-iron ladle",
    "boning knife",
    "tin of rat poison",
    "rolling pin",
    "carving fork",
    "length of apron cord",
    "steel stockpot",
    "fire extinguisher",
    "bottle of degreaser",
    "meat tenderizer",
    "honing steel",
  ],
};

export const THEMES: ThemeContent[] = [MANOR_THEME, FARM_THEME, CAMP_THEME, MESS_HALL_THEME];

/** Looks a theme pack up by its @kdp/shared theme id, falling back to the manor. */
export function themeById(id: string | undefined): ThemeContent {
  return THEMES.find((theme) => theme.id === id) ?? MANOR_THEME;
}
